<a href="https://colab.research.google.com/github/gnidetsanna/python_for_ML_tasks/blob/main/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_hnidets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [58]:
import numpy as np

In [77]:
a = np.random.rand(10,)
vector = np.array(a)
print("\nВектор-стовпець vector:")
print(vector)
print("\nРозмірність вектора vector:")
print(vector.shape)


Вектор-стовпець vector:
[0.77059262 0.00559876 0.20139708 0.6265354  0.66814984 0.53537664
 0.82937872 0.66836526 0.01131033 0.91921246]

Розмірність вектора vector:
(10,)


In [78]:
matrix = np.array([[11,14,17],
                   [20,23,26],
                   [29,32,35]])
print("Матриця matrix:")
print(matrix)
print("\nРозмірність матриці matrix:")
print(matrix.shape)

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмірність матриці matrix:
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [79]:
np.round(vector+10,2)

array([10.77, 10.01, 10.2 , 10.63, 10.67, 10.54, 10.83, 10.67, 10.01,
       10.92])

In [80]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [81]:
new_vector = np.square(vector)
new_vector

array([5.93812983e-01, 3.13461057e-05, 4.05607837e-02, 3.92546614e-01,
       4.46424212e-01, 2.86628149e-01, 6.87869060e-01, 4.46712125e-01,
       1.27923514e-04, 8.44951544e-01])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [82]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

 Кількість стовпців першої матриці (матриця A) має співпадати з кількістю рядків другої матриці (В) тому треба множити B,A де Bстопвців 3, на Арядків 3

In [83]:
result_matrix = np.dot(B,A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Результуюча матриця в нас 2 на 2, а вектор С 2 на 1. Тобто якщо множити result_matrix на vector - нова матриця в нас буде Result_matrix_рядки на Vector_стовпці - 2 на 1

Навпаки не помножиться, бо кількість стовців вектора 1 а кількість рядків матриці 2

In [84]:
np.dot(result_matrix,C)

array([[0.5202],
       [0.2846]])

Матриця result_matrix 2 на 2, матриця D 2*2 - буде 2 на 2 бо кількість стовпчиків першої матриці = кількість рядків 2.

In [85]:
np.dot(result_matrix,D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

In [86]:
np.dot(D,result_matrix)

array([[0.2034, 0.2846],
       [0.7281, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [87]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [90]:
vector.T , (vector.T).shape

(array([0.77059262, 0.00559876, 0.20139708, 0.6265354 , 0.66814984,
        0.53537664, 0.82937872, 0.66836526, 0.01131033, 0.91921246]),
 (10,))

Зміни не бачу
В NumPy одновимірні масиви, тобто вектори, не змінюються при застосуванні методу транспонування .T. Це відбувається через те, що одновимірний масив не має осей для транспонування

In [91]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, vector

(array([[0.77059262],
        [0.00559876],
        [0.20139708],
        [0.6265354 ],
        [0.66814984],
        [0.53537664],
        [0.82937872],
        [0.66836526],
        [0.01131033],
        [0.91921246]]),
 array([0.77059262, 0.00559876, 0.20139708, 0.6265354 , 0.66814984,
        0.53537664, 0.82937872, 0.66836526, 0.01131033, 0.91921246]))

Тепер і справді вектор транспонувався

In [92]:
trans_c_vector = column_vector.T
trans_c_vector, trans_c_vector.shape

(array([[0.77059262, 0.00559876, 0.20139708, 0.6265354 , 0.66814984,
         0.53537664, 0.82937872, 0.66836526, 0.01131033, 0.91921246]]),
 (1, 10))

Транспонування відбулось